### ISSUE TITLE
Find Potential References to Row

### ISSUE THREAD

**Issue by FirestarJes** [SnosMe/poe-dat-viewer#19]
It would be a nice feature, to stand on a row, and then be able to do a reverse lookup, finding potential files which references this row.

Could be done by going through all known "refrence fields/arrays of references" and finding those which has a value corresponding to the selected rows index.

**Comment by SnosMe** [comment]
This was always possible, just need to preload tables first.

![image](https://github.com/SnosMe/poe-dat-viewer/assets/4292308/26b264b0-6db2-4cf2-ad0b-4c15d75ebee4)
