### ISSUE TITLE
decompressSliceInBundle is not async safe

### ISSUE THREAD

**Issue by d07RiV** [SnosMe/poe-dat-viewer#21]
It's more of an issue of ooz-wasm lib, but since it doesn't have issues enabled I'm posting it here.

`decompressUnsafe` is so unsafe that it's unusable unless you have no parallel execution at all, because it requires processing output synchronously, while promises are always resolved asynchronously. So two calls to `decompressSliceInBundle` (or `FileLoader.getFileContents`) at the same time will always result in corrupted data.

`decompress` causes a runtime error, since it attempts to call `module._free`, but in this case `module` refers to global Node module and not to wasm module.

The best way to fix it (if the goal is to avoid unnecessary data copying) IMO is to pass a callback to process data synchronously before freeing memory. I made these changes in a fork @ https://github.com/d07RiV/ooz-wasm/commit/7be502e858d68f5af70766cbc2c26a95bdebc9a2 but I can't make a PR since I had to add build folder into the repo for npm to work.

**Comment by SnosMe** [comment]
Sorry for the late response.
Thanks to nodejs supporting ESM modules for quite some time now, I've changed how WASM module is instantiated, so there is no more async signature in ooz-wasm APIs.
